name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

concurrency:
  group: renovate-${{ github.repository }}
  cancel-in-progress: false

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: renovatebot/github-action@v46.1.17
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}